language: python

matrix:
  fast_finish: true
  include:
    - python: 3.1
      env: comment="3.1 as float"
    - python: 3.10
      env: comment="3.10 as float"
    - python: "3.1"
      env: comment="3.1 as string"
    - python: "3.10"
      env: comment="3.10 as string"

install:
 - pip install -U tqdm

script:
  - echo "$DIST"
  - lsb_release -a
  - python --version
  - python ./test.py
